#!/usr/bin/env bash
set -e

if [ $# -lt 2 ]; then
    echo "Insufficient args. Usage: run_remote_docker OUT_FOLDER VERSION [...]"
fi

real=$(realpath $1)
shift 1
version=$1
shift 1

docker run -it --rm -v "$real:/app/out" "cmalabscience/mtpdb:$version" "/app/out" $@
