#!/usr/bin/env bash
set -e

if [ $# -lt 1 ]; then
    echo "Insufficient args. Usage: run_rebuilder OUT_FOLDER [...]"
fi

real=$(realpath $1)
shift 1

docker run -it --rm -v $real:/app/out mtpdb:bleeding "/app/out" $@
