#!/usr/bin/env bash
set -e

if [ $# -lt 1 ]; then
    echo "Insufficient args. Usage: run_rebuilder OUT_FOLDER [...]"
fi

if [ -z ${1+x} ]; then
    echo "Missing output directory. Aborting.";
    exit 1
fi

if [ ! -d ${1} ]; then
    echo "Target is not a directory. Aborting";
    exit 1
fi

real=$(realpath $1)
shift 1

docker run -it --rm -v $real:/app/out dbrebuilder:latest "/app/out" $@
