#!/usr/bin/env bash
set -e

temporary=$(mktemp -d)

docker build . --tag dbrebuilder:bleeding --target test

if [ "$1" = "--all" ]; then
    docker run -v $temporary:/app/out dbrebuilder:bleeding --runslow
else
    docker run -v $temporary:/app/out dbrebuilder:bleeding
fi
